sonar.projectKey=Plutoaintaplanet_carml2
sonar.organization=plutoaintaplanet
sonar.host.url=https://sonarcloud.io
sonar.sources=CARML
sonar.language=py
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/__pycache__/**,**/*.pyc,**/*.md,.git/**
